name: Cleanup Closed PR Deployments

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Fetch all closed PRs
        id: fetch-closed-prs
        run: |
          # Fetch all closed PRs using the GitHub API
          CLOSED_PR_NUMBERS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed" \
            | jq -r '.[].number' | tr '\n' ' ')  # Replace newlines with spaces
            
          # Properly format the output for GitHub Actions
          echo "closed_pr_numbers=${CLOSED_PR_NUMBERS}" >> $GITHUB_OUTPUT
  
      - name: Remove directories for closed PRs
        run: |
          # Loop through all PR directories and delete those for closed PRs
          for PR_DIR in pr-*; do
            PR_NUMBER=${PR_DIR#pr-}  # Extract PR number from directory name
            if echo "${{ steps.fetch-closed-prs.outputs.closed_pr_numbers }}" | grep -qw "$PR_NUMBER"; then
              echo "Removing directory for closed PR: $PR_DIR"
              rm -rf "$PR_DIR"
            else
              echo "PR $PR_NUMBER is not closed. Skipping directory: $PR_DIR"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Cleanup: Remove directories for closed PRs"
          git push origin gh-pages